# Evaluator parameters
output_dir: ./evaluation_results/gpt_rag
overwrite_output_dir: False

run_arguments:
  internal_language: es
  output_language: es
  location: es
  generate_image: False
  answer_questions: False

workflow_config: ./configs/pipeline_configs/gpt_rag.yaml