# Evaluator parameters
output_dir: ./evaluation_results/latxa8b-4bit_rag_gpt
overwrite_output_dir: False

run_arguments:
  internal_language: es
  output_language: es
  location: es
  generate_image: False
  answer_questions: False

workflow_config: ./configs/pipeline_configs/latxa8b_rag_gpt.yaml