# Evaluator parameters
output_dir: ./evaluation_results/latxa4b_vl_rag.yaml
overwrite_output_dir: False

run_arguments:
  internal_language: es
  output_language: es
  location: es
  generate_image: False
  answer_questions: False

workflow_config: ./configs/pipeline_configs/latxa4b_vl_rag.yaml